### ISSUE TITLE
Substitute rocksdb write stall

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#10137]
## Development Task
When TiKV write stall occurs, it usaully blocks all the following write requests, which incurs a dramatic QPS drop. To mitigate the sudden spike, we try to disable the RocksDB write stall and add a dynamic write controller to control the write rate at scheduler level smoothly.

[design document](https://github.com/tikv/rfcs/pull/67)

### Task breakdown:

- [x] Find a case to reproduce write stall steadily
- [ ] Evaluate the design under single TiKV instance setup
  - [ ] Compare master with the case that write stall is disabled
  - [ ] Compare master with the case that higher delay write rate is set
  - [ ] Implement the design, compare it with the above two cases
- [ ] Test under multiple TiKV instances setup
  - [ ] The case that write stall only occurs on some TiKV instances, not all
  - [ ] The case that pending-compaction-bytes changes a lot after dropping table
  - [ ] The case that balance region causes too many L0

**Comment by tisonkun** [comment]
@Connor1996 you can easily refer this issue from subtask by `ref #10137` which makes use of GitHub mechanism and avoid maintaining the checklist above. I think that checklist is extremely easy to be outdated.

**Comment by tisonkun** [comment]
You can take a look at 

* https://github.com/pingcap/tidb/issues/24169
* https://github.com/tikv/community/issues/118

as examples.
