### ISSUE TITLE
GSoC: TLA+ Specification for Async Commit

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#10319]
## Description

The [TiKV](https://github.com/tikv/tikv) has recently been launching a new feature in the transaction model named [Async commit](https://github.com/tikv/sig-transaction/tree/master/design/async-commit). It's an optimization that reduces the commit latency from 2PC to 1PC. However, this feature has not been reflected in the [TLA+ Specs](https://github.com/pingcap/tla-plus/tree/master/DistributedTransaction).

This GSoC program is to update the spec and then running TLC model checker on the new model to gain more confidence on the async commit design.

## Document Collection

- [Async Commit design doc (Chinese)](https://docs.google.com/document/d/1VRkxwij-oXDra8oaKdnTH5zn7FdOQPw9OudM3mkp2Kw/edit)
- [Pessimistic lock design doc (Chinese)](https://docs.google.com/document/d/1uOtA6fpzkr50w1VdIIy7YzRAcXjdiJUX0dgGhXy7bDc/edit)

## Talent Challenge Program information

- Mentor of this issue: @andylokandy
- Recommended skills: TLA+ / Golang / Rust
- Estimated Workloads: 3 Man-Month

## Milestones and action items

Milestone 1: Update the specification to the last transaction model before async commit, Expected finish date: July 2021

- [ ] Add the `CheckTxnStatus` command and deprecate the `Cleanup` command.
- [ ] Refactor the specification (rename / restructure).
- [ ] Add invarient for checking snapshot read. (Optional)

Milestone 2: Add async commit to the specification, Expected finish date: September 2021

- [ ] Add async commit prewrite
- [ ] Add async commit resolve lock
- [ ] Add 1PC
- [ ] Add async commit fallback

**Comment by BusyJay** [comment]
Cool! TiKV has its owned [tla spec repo](https://github.com/tikv/tlaplus-specs), can you submit the changes there?

**Comment by zhuo1angT** [comment]
> Cool! TiKV has its owned [tla spec repo](https://github.com/tikv/tlaplus-specs), can you submit the changes there?

Hi, Jay. Currently, I'm working on [this repo](www.github.com/pingcap/tla-plus), the DistributedTransaction sub-dir. Is there anything I should do on the one you mentioned?

**Comment by krfong916** [comment]
Hi @ekexium @andylokandy and @zhuo1angT 
Are you still working on providing model checking for TiKV's async commit? What milestones have you already completed? I'd love to work on this issue if there is still work to complete

**Comment by ekexium** [comment]
Hi @krfong916, thank you for your interest! I've been away from the project for some time. I think the last PR is not  landed yet. [@zhuo1angT 's summary](https://gist.github.com/zhuo1angT/aeb48e10d4437e076bfdd5a505ec94cc) states what we had done and might help.
