### ISSUE TITLE
Tracking issue of CDC flow control refactor

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10374]
## Development Task

The original CDC flow control implementation (#9885) has been refactored by the following PRs:

* Add scan speed limiter. #10108
* Set an upper bound of an internal channel used in CDC #10142
* Add memory quota to CDC and kill connection if it uses too much memory #10135

There are some changes in #9885 that have not yet been merged into the master branch:

- [ ] Send real-time events in a higher priority than incremental scan events.
- [ ] Tolerate region split/merge and leader step down during incremental scan.
- [ ] Always generate resolved ts after incremental scan.  
- [ ] Drop entire Eventfeed RPC when meltdown is triggered.
