### ISSUE TITLE
Support online recovery for Raft majority failure

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#10483]
## Development Task

Currently, we have a tool to recover Raft groups from majority failure:
```
tikv-ctl unsafe-recover remove-fail-stores -s <store_id, store_id> …
tikv-ctl recreate-region -r <region_id> ...
```

The first command is used to recover Raft groups of which the majority but not all replicas failed. Its mechanism is removing failed stores from membership configurations of those Raft groups.

The second command is used to recover Raft groups of which all replicas failed. Before running the command we need to find those Raft groups, which is not a documented routine. So there are no users who can do this recovery without our DBAs’ help.
Both of the 2 commands should be run on stopped TiKV instances, which makes the recovery process so long and complex that not all users can perform all steps correctly.

And there are some corner cases that could lead to inconsistent membership configuration among all replicas. If the Region splits later, this mistake will lead to inconsistent Region boundaries, which is very hard to locate and fix.
So we need to re-design and re-implement a new feature to recover a TiKV cluster from majority failure. The feature should be:
- able to be executed online
- able to avoid all inconsistencies
- a feature instead of a tool, focus on Raft majority failure, shouldn’t be used for other situations
- easy to use, at most 1 or 2 steps or command

### Specs
We must know there are no silver bullets for Raft majority failure. There must be something lost after a TiKV cluster recovers from that. Considering such integrations or consistencies:
- Committed writes  can be lost, so linear consistency of Raft can be broken;
- Some prewrites can be lost for a given transaction, so Transaction Atomicity and/or Consistency can be broken;
- Commits can be lost for a given transaction, so Transaction Consistency and/or Durability can be broken;
- For a given table, both records or indices can be lost, so Data Consistency can be broken;
- For a given transaction, it can be partially committed, so Data Integrity can be broken.

#### Stage 1: Implement basic online recovery 
- [x] Add `recover-store-failure` command of pd-ctl https://github.com/v01dstar/pd/pull/1
- [x] Add framework of unsafe recovery worker in PD  https://github.com/v01dstar/pd/pull/2
- [x] Support `DumpUnavailableRegions` command
  - [x] Change `StoreHeartbeatRequest` and `StoreHeartbeatResponse` in kvproto  https://github.com/v01dstar/kvproto/pull/1
  - [x] Dispatch it by `StoreHeartbeatResponse` in PD https://github.com/v01dstar/pd/pull/2
  - [x] Handle it and return results in TiKV https://github.com/v01dstar/tikv/pull/1
- [x] Implement the logic of unsafe recovery worker in PD(only keep one replica) https://github.com/tikv/pd/pull/4238
- [x] Support `UnsafeRecovery` command https://github.com/tikv/tikv/pull/11146
  - [x] Add a new API in kvproto
  - [x] Implement logic in TiKV
- [x] Support `RecreateRegion` command https://github.com/tikv/tikv/pull/11146
  - [x] Add a new API in kvproto
  - [x] Implement logic in TiKV 
- [x] Test [5d]
- [x] Add recovery document https://github.com/pingcap/docs-cn/pull/7381

#### Stage 2: Make the best effort for the case of replicas more than 3
- [x] Forbid the removed stores starting again https://github.com/tikv/pd/pull/4338 @v01dstar 
- [x] PD disables the schedule operations in the recovery process https://github.com/tikv/pd/pull/4475 @v01dstar 
- [x] TiKV makes sure commit index == apply index https://github.com/tikv/tikv/pull/11716 @v01dstar ‘
  - [x] Fix snapshot corner case https://github.com/tikv/tikv/pull/12308 @v01dstar 
- [x] Avoid PD issuing peer report again and again https://github.com/tikv/pd/pull/4705 @v01dstar 
- [x] Dispatch recovery plan by raft and execute in apply https://github.com/tikv/tikv/pull/12022 @v01dstar
  - [x] Modify proto https://github.com/pingcap/kvproto/pull/904 @Connor1996 
  - [x] Report unapplied commit merge, to let force leader on region of commit merge first https://github.com/tikv/tikv/pull/12638
  - [x] Fix https://github.com/tikv/tikv/issues/12506
- [x] Adjust the logic of unsafe recovery worker in PD and divide the process into multiple stages https://github.com/tikv/pd/pull/4704 @Connor1996 
  - [ ] Make region tree generic (optional)
  - [ ] Send store heartbeat response actively (optional)
  - [x] Tombstone tiflash learner peer if it's latest https://github.com/tikv/pd/pull/5045
  - [x] Fix blocking on exit force leader https://github.com/tikv/pd/pull/4982
- [x] Implement `force_leader` https://github.com/tikv/tikv/pull/11932 @Connor1996 
  - [x] Fix hibernated peer case https://github.com/tikv/tikv/pull/12364
  - [x] Fix related flaky tests and add back exit force leader check https://github.com/tikv/tikv/pull/12810
  - [ ] Fix corner case: supposing (a, b, c, d, e) -> (a, b, c, d, f) -> (a, b, c, g, f), and a, b, g, f all fail. c is isolated during the whole time. It may think it still has quorum (c, d, e)
  - [x] Add `RecoveryInProgress` error https://github.com/pingcap/kvproto/pull/863 @Connor1996
  - [x] Handle `RecoveryInProgress` error in client https://github.com/tikv/client-go/pull/485 @Connor1996
  - [x] Dynamic change `check_quorum` of raft https://github.com/tikv/raft-rs/pull/461 @v01dstar 
- [ ] ~~Invalidate region cache in clients after recovery (optinal)~~
- [x] Public RFC https://github.com/tikv/rfcs/pull/91
- [x] Update doc https://github.com/pingcap/docs-cn/pull/9495
- [x] Adaption of Tiflash https://github.com/pingcap/tidb-engine-ext/pull/62
- [x] Test

#### Stage 3: Enhance inconsistency fix tools (Optional）
- [ ] Adjust `recover-mvcc` tool to handle the case the primary key lock and secondary key locks are not consistent after unsafe recovery
- [ ] Make TiDB admin recover table differential
  - [ ] Need more detailed design,TBD

**Comment by yiwu-arbug** [comment]
@Connor1996 can you add time estimation and also prioritization? Like I think we agree that `force_leader` is optional.

Also some missing tasks:
* (pointed out by Liquan) benchmark the recovery time.
* document (we may need to describe things like how inconsistency in secondary index and and mvcc can be handled in another tool, etc)
* breakdown of test
* handle TiFlash compatibility

**Comment by Connor1996** [comment]
@yiwu-arbug 
- Update the breakdown of the test, including benchmark the recovery time.
- The prioritization follows the stage. Stage 2 is actually some subtasks of `force_leader`. 
- For the inconsistency fixing tool, let's discuss later. As expected, we won't be able to do them in this sprint.
- For TiFlash compatibility, it's just a detailed design in `Implement the logic of unsafe recovery worker in PD(only keep one replica)`. Won't refer to it in general task breakdown.

**Comment by yiwu-arbug** [comment]
yes, consistency fixing is out of scope of this project. but I do feel necessary to provide a recovery guide based on existing tools, and that should be part of this project.

**Comment by Connor1996** [comment]
Agree, add it

**Comment by tisonkun** [comment]
@Connor1996 it seems none of item in the task list done. Is there something out of sync?

**Comment by Connor1996** [comment]
@v01dstar Please update the task list if there is a PR

**Comment by tisonkun** [comment]
@Connor1996 I think people without write permission just cannot edit the description, you can have a discussion or let @v01dstar comments here so that we can reflect progress.

**Comment by v01dstar** [comment]
### Task Breakdown
#### Stage 1: Implement basic online recovery
* [x]  Add `recover-store-failure` command of pd-ctl [1d] [Recover v01dstar/pd#1](https://github.com/v01dstar/pd/pull/1)
* [x]  Add framework of unsafe recovery worker in PD [3d] [Adds unsafe recovery worker/controller v01dstar/pd#2](https://github.com/v01dstar/pd/pull/2)
* [ ]  Support `DumpUnavailableRegions` command
  
  * [x]  Change `StoreHeartbeatRequest` and `StoreHeartbeatResponse` in kvproto [1d] [Prototype of unsafe recovery commands proto v01dstar/kvproto#1](https://github.com/v01dstar/kvproto/pull/1)
  * [ ]  Dispatch it by `StoreHeartbeatResponse` in PD [2d]
  * [x]  Handle it and return results in TiKV [5d] [Reporting detailed store states v01dstar/tikv#1](https://github.com/v01dstar/tikv/pull/1)
  * [x]  Implement the logic of unsafe recovery worker in PD(only keep one replica) [2d] [Generating recovery plan based on the store reports v01dstar/pd#3](https://github.com/v01dstar/pd/pull/3)
* [ ]  Support `UnsafeRecovery` command
  
  * [ ]  Add a new API in kvproto [1d]
  * [ ]  Implement logic in TiKV [5d]
* [ ]  Support `RecreateRegion` command
  
  * [ ]  Add a new API in kvproto [1d]
  * [ ]  Implement logic in TiKV [5d]
* [ ]  Test [5d]
  
  * [ ]  Benchmark the recovery time
* [ ]  Add recovery document [1d]

**Comment by Connor1996** [comment]
> ### Task Breakdown
> #### Stage 1: Implement basic online recovery
> * [x]   Add `recover-store-failure` command of pd-ctl [1d] [Recover v01dstar/pd#1](https://github.com/v01dstar/pd/pull/1)
> * [x]   Add framework of unsafe recovery worker in PD [3d] [Adds unsafe recovery worker/controller v01dstar/pd#2](https://github.com/v01dstar/pd/pull/2)
> * [ ]   Support `DumpUnavailableRegions` command
>   
>   * [x]   Change `StoreHeartbeatRequest` and `StoreHeartbeatResponse` in kvproto [1d] [Prototype of unsafe recovery commands proto v01dstar/kvproto#1](https://github.com/v01dstar/kvproto/pull/1)
>   * [ ]   Dispatch it by `StoreHeartbeatResponse` in PD [2d]
>   * [x]   Handle it and return results in TiKV [5d] [Reporting detailed store states v01dstar/tikv#1](https://github.com/v01dstar/tikv/pull/1)
>   * [x]   Implement the logic of unsafe recovery worker in PD(only keep one replica) [2d] [Generating recovery plan based on the store reports v01dstar/pd#3](https://github.com/v01dstar/pd/pull/3)
> * [ ]   Support `UnsafeRecovery` command
>   
>   * [ ]   Add a new API in kvproto [1d]
>   * [ ]   Implement logic in TiKV [5d]
> * [ ]   Support `RecreateRegion` command
>   
>   * [ ]   Add a new API in kvproto [1d]
>   * [ ]   Implement logic in TiKV [5d]
> * [ ]   Test [5d]
>   
>   * [ ]   Benchmark the recovery time
> * [ ]   Add recovery document [1d]

I will sync all the following PRs, no need to comment anymore.
