### ISSUE TITLE
Tracking issue of TiKV disk full

### ISSUE THREAD

**Issue by tier-cap** [tikv/tikv#10537]
## Development Task

This issue describes a new feature that makes TiKV can avoid panicking from disk full failure, and provide space reclamation support at the same time. The spec:
* TiKV shouldn't panic even if its disk usage is almost full
* Even if most TiKV instances in a cluster are almost full, the cluster should be still readable.
* Even if most TiKV instances in a cluste are almost full, users should still can release space by `drop table` or `truncate table`.

## Task list

* [x] #10597
* [x] https://github.com/pingcap/tidb/issues/27665
* [x] https://github.com/tikv/client-go/issues/286
* [x] https://github.com/pingcap/kvproto/issues/803
## Bug List
* [x] https://github.com/tikv/tikv/issues/10960
* [x] https://github.com/tikv/tikv/issues/10959
* [x] https://github.com/tikv/tikv/issues/10926
* [x] https://github.com/tikv/tikv/issues/10925
* [x] https://github.com/tikv/tikv/issues/10895
* [x] https://github.com/tikv/tikv/issues/10894
* [x] https://github.com/tikv/tikv/issues/10868
* [x] https://github.com/tikv/tikv/issues/10840
* [x] https://github.com/tikv/tikv/issues/10839
* [x] https://github.com/tikv/tikv/issues/10819
* [x] https://github.com/tikv/tikv/issues/10801

## Left & Low Priority
* [ ] https://github.com/tikv/tikv/issues/11010
* [ ] https://github.com/tikv/tikv/issues/10665
* [ ] https://github.com/tikv/tikv/issues/11109
* [ ] https://github.com/tikv/tikv/issues/11110
* [ ] https://github.com/tikv/tikv/issues/11232
* [ ] https://github.com/tikv/tikv/issues/11236
* [ ] https://github.com/pingcap/tidb/issues/29557

**Comment by tisonkun** [comment]
Hi @tier-cap ! Thanks for creating this tracking issue. You may create issue for each subtask dedicatedly, see also https://github.com/pingcap/tidb/issues/26022 . The rationale of tracing issues instead of pull requests can be found [here](https://tisonkun.github.io/ziggurat/f379bf788b20/#Issus-or-Pull-Request).

For example, you may create an issue that gets closed once #10562 resolved.

**Comment by tisonkun** [comment]
we are tracking issue by issues, why do you update the description redundant to show PRs?

**Comment by DanielZhangQD** [comment]
For some users that only have small disks, e.g. 10GB disk, it's really necessary to have the features in this issue to improve the disk usage ratio and the stability of the TiDB clusters.
