### ISSUE TITLE
Introduce slow node detecting mechanism

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#10539]
Tracking issue for slow node detection

# Background 
As the scale of the tikv cluster becomes larger, the frequency of failures that slow down a single tikv (known as fail-slow) due to various reasons will become higher (according to the 1.02% annual failure rate[1], as a rough estimate, if the total number of nodes running tikv for all customers is 5k, then we will encounter this problem almost every week). Therefore, we need a more timely mechanism to discover and automatically cope with those problems as much as possible to improve the stability of TiKV clusters.

# Task
- [x] Collect how tikv performs after some components become slow
- [x] Design and implement a mechanism to measure the performance of a tikv
- [x] Introduce a mechanism to mitigate fail-slow

**Comment by tisonkun** [comment]
@5kbpers on the [monthly meeting](https://internals.tidb.io/t/topic/363/2) @BusyJay said this feature is released in 5.2, but it seems there is still

> Introduce a mechanism to mitigate fail-slow

under development. Is there anything PR actually implement it?

**Comment by 5kbpers** [comment]
> @5kbpers on the [monthly meeting](https://internals.tidb.io/t/topic/363/2) @BusyJay said this feature is released in 5.2, but it seems there is still
> 
> > Introduce a mechanism to mitigate fail-slow
> 
> under development. Is there anything PR actually implement it?

Yes, you can check those PRs refer to this issue.

**Comment by 5kbpers** [comment]
Close since this work has done.
