### ISSUE TITLE
Support limiting read flow for TiKV IO rate limiter

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#10867]
## Description

Before, we added an [io snooper supported by BPF](https://github.com/tikv/tikv/pull/9153) to get the actual read flow categorized by threads. With the limitation of BPF that needs sudo permission, it isn't used in production actually.

Actually, [proc](https://man7.org/linux/man-pages/man5/proc.5.html) provides a simpler way to get the actual read flow categorized by threads by `/proc/<pid>/task/<tid>/io/read_bytes`.

## Document Collection

- Weekly report: ${weekly report link}

## Talent Challenge Program information

- Mentor of this issue: @Connor1996 
- Recommended skills: Rust, Linux
- Estimated Workloads: 1XL(XL, man-month)

## Milestones and action items

Milestone 1: Expected finish date: ${0.5XL}

- [ ] Collect the actual read flow by `proc` https://github.com/tikv/tikv/pull/11667
- [ ] Remove the entrance of enabling io snooper  https://github.com/tikv/tikv/pull/11394
- [ ] Adjust grafana template
- [ ] Fix https://github.com/tikv/tikv/issues/10659

Milestone 2: Expected finish date: ${0.5XL}

- [ ] Test
