### ISSUE TITLE
Integrate with raft engine

### ISSUE THREAD

**Issue by tabokie** [tikv/tikv#11119]
## Development Task

TiKV subtask of tikv/raft-engine#95

- [x] Support write batch interfaces: `persist_size()`, `merge(rhs)`: https://github.com/tikv/raft-engine/pull/82, https://github.com/tikv/raft-engine/pull/122
- [x] Issue IO requests through IO rate limiter: #10937
- [ ] Tag IO in threads owned by raft engine
- [x] Support encryption at rest: #10937
- [x] Add Grafana monitoring: #11415

**Comment by ztelur** [comment]
Hi! I am interested in raft. Is there some work I can contribue to ?

**Comment by tabokie** [comment]
@ztelur Hi and welcome. The TiKV part of tikv/raft-engine#95 is almost done, you can still contribute to raft-engine.

Right now we are looking to releasing raft-engine in upcoming release (5.4.0), so code quality is the priority here. It basically boils down to two tasks:
1) Refactor critical code paths, add unit tests and assertions.
2) Implement "emergency exit" to handle possible data inconsistency caused by bug or disk corruption.

Other than these two, you can also contribute to a performance-oriented task: make raft engine supports multiple WALs. It's not yet on the roadmap, but we can discuss the details if you are interested.

**Comment by ztelur** [comment]
@tabokie ok
