### ISSUE TITLE
Tracking Issue: In-memory Pessimistic Locks

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#11452]
RFC: https://github.com/tikv/rfcs/pull/77

## Development Task

- [x] https://github.com/tikv/tikv/pull/11459
- [x] https://github.com/tikv/tikv/pull/11471
- [x] https://github.com/tikv/tikv/pull/11481
- [x] https://github.com/tikv/tikv/pull/11529
- [x] https://github.com/tikv/tikv/pull/11591
- [x] https://github.com/tikv/tikv/pull/11577
- [x] https://github.com/tikv/tikv/pull/11841
- [x] https://github.com/tikv/tikv/pull/11883
- [x] https://github.com/tikv/tikv/pull/11655
- [x] https://github.com/tikv/tikv/pull/11985
- [x] https://github.com/tikv/tikv/pull/11758
- [x] https://github.com/tikv/tikv/pull/12089
- [x] https://github.com/tikv/tikv/pull/12078
- [ ] https://github.com/tikv/tikv/pull/12153
