### ISSUE TITLE
Tracking issue for making region size dynamic

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#11515]
RFC: https://github.com/tikv/rfcs/pull/82

Summary: 

Make the size of a region dynamic, and only set a upper limit.

This is the first step that we try to support PB scale cluster.

Tasks:

- [ ] PD uses cost estimation based on size instead of a hard coded value
- [ ] PD schedules well on both size balance and load balance.
- [ ] TiKV supports buckets
- [ ] TiKV/PD support processing flow report in a standalone stream
- [ ] PD uses buckets to do hotspot split and deprecated TiKV local hotspot split
- [ ] TiKV side concurrency for coprocessor requests
- [ ] Warming up in pretransfer leader
- [ ] Infinite leader lease
- [ ] Lightening/BR presplit reconfiguration based on the new size
- [ ] (Optional) more efficient snapshot generation and apply

The feature is expected to be disabled by default when release as it may bring extra replication cost in current architecture.

The task item may change as the proposal is not approved yet.

**Comment by bufferflies** [comment]
Can these tasks be closed?
