### ISSUE TITLE
Roadmap for stage latency statistics

### ISSUE THREAD

**Issue by mornyx** [tikv/tikv#11525]
## Description

We now have stage-latency-stats of KvGet/KvBatchGet, but there are still several necessary tasks to be done. This issue is used to track these tasks.

## Tasks

- [x] Add stage-latency-stats for KvGet/KvBatchGet.
    - https://github.com/tikv/tikv/issues/8942
    - https://github.com/tikv/tikv/pull/11508

- [ ] Integrate latency stats mechanism.
    - We have introduced stage-latency-stats for KvGet/KvBatchGet in the `storage` layer, but there is already a mechanism in the `service` layer to count the latency of the storage layer interface as black box. We need to integrate them to maintain consistency.

- [ ] Use these new latency indicators in TiDB.
    - We now have `schedule_wait_time`, `snapshot_wait_time`, `wait_wall_time` and `process_wall_time`, but the `schedule_wait_time` and `snapshot_wait_time` are not returned to TiDB, we need to leverage the value of these indicators in TiDB.

- [ ] Supports stage-latency-stats for more interfaces.
    - We need to support stage-latency-stats for more interfaces. Note that the various stages in the introduced `StageLatencyStats` may not match some special interfaces, which requires additional design.
