### ISSUE TITLE
Implement RawKV Cross Cluster Replication

### ISSUE THREAD

**Issue by pingyu** [tikv/tikv#11965]
## Development Task

Issue Number: #11745 
RFC: https://github.com/tikv/rfcs/pull/86

##### Development:

- [x] API v2: @pingyu #12036
  - [x] New RawKV key codec
- [x] Raw store: @haojinming #12087
- [x] Causal timestamp: @pingyu #12099
  - [x] Timestamp allocation
  - [x] Timestamp management
    - [x] Advance timestamp on leader transfer
  - [x] Server
    - [x] Feature switch & configuration
- [x] Raw interfaces: @pingyu #12343 
  - [x] Reads
  - [x] Writes
  - [x] Deletes @haojinming #12090
  - [x] Atomic
- [x] Garbage collection: @ystaticy 
  - [x] TiKV gc_worker #12424 
  - [x] Standalone GC worker @haojinming https://github.com/tikv/migration/pull/85
- [x] BR for cross API version data migration
  - [x] TiKV br component #12303 
  - [x] TiKV-BR https://github.com/tikv/migration/issues/67
- [x] Others
  - [x] Bulk load #12389 
  - [x] Metrics #12494 

##### Testing: 

- [x] Test
  - [x] Integration Test for causality validation
    - [x] Leader Transfer
    - [x] Region split + leader transfer
    - [x] Region merge + leader transfer
- [x] Benchmark: baseline (v5.5-alpha) v.s. API v2, observing QPS and P99 latency
  - [x] raw_put
  - [x] raw_delete
  - [x] raw_get

#### Phase 2 (CDC):

- [x] CDC component @zeminzhou
  - [x] Rawkv procedure #12387
    - [x] Raw changefeed (receive rawkv changefeed from TiKV-CDC)
    - [x] Incremental scan
    - [x] Raw sink (send rawkv data to TiKV-CDC)
  - [x] Resolved_ts #12866
- [x] Metrics
    - [x] TiKV-CDC Grafana board https://github.com/tikv/migration/pull/130
    - [x] Resolved-ts metrics
- [x] Test
  - [x] Integration Test for causality validation
    - [x] TiKV - CDC - TiKV
    - [x] Leader Transfer
    - [x] Region split + leader transfer
    - [x] Region merge + leader transfer
- [x] Benchmark: baseline (v5.5-alpha) v.s. CDC feature disabled v.s CDC feature enabled, observing QPS and P99 latency
  - [x] raw_put
  - [x] raw_delete
  - [x] raw_get

### Development Guide
1. Choose a sub-task you are interested in.
2. File a ISSUE for the sub-task.
3. Fix the ISSUE and file the PR.
4. Get the PR merged.

**Comment by ztelur** [comment]
> > @pingyu Hi, I am interested in this task, if there are any tasks that can be assigned?
> 
> Thanks for your willing of contribution ! But I'm sorry that all tasks are under development now. Or would you like to help reviewing RFC & PRs ? All links can be found in the issue description.

Ok
