### ISSUE TITLE
Tracking Issue for Load Base Split Improvement

### ISSUE THREAD

**Issue by JmPotato** [tikv/tikv#12063]
As mentioned in https://github.com/tikv/pd/issues/4588, Load Base Split can not work well in most or pure scan scenarios. We need to introduce more statistical dimensions to the Load Base Split decision process, such as statistics related to the read CPU usage. This is the tracking issue for some related work.

## Steps

- [x] Add key ranges in read CPU usage collecting (https://github.com/tikv/tikv/issues/11988)
- [x] CPU usage collecting
	- [x] ~gRPC Poll CPU utilization collecting (https://github.com/tikv/tikv/issues/12139)~
- [x] CPU usage-based split process (https://github.com/tikv/tikv/pull/12593)
	- [x] https://github.com/tikv/tikv/issues/12937
	- [x] https://github.com/tikv/tikv/pull/12942
	- [x] https://github.com/tikv/tikv/issues/12943
	- [x] https://github.com/tikv/tikv/pull/12955
	- [x] https://github.com/tikv/tikv/pull/12969

## Unresolved Questions

- [ ] **Observer & Metrics**: We need to settle a way to observe the Load Base Split behavior to help us debug and check the split results.
- [x] ~**Cost Model**: A cost model is needed to evaluate and determine the split effect between the read pool and gRPC poll CPU.~
- [x] **Switch & Mechanism**: What kind of switch or mechanism it should be like to control the CPU usage collecting?
- [ ] **Feedback Functionality**: tikv/pd#5267
