### ISSUE TITLE
Support 2 Replicas With 1 Log Only Mechanism

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#12876]
## Development Task

On cloud env, TiKV is equipped with AWS EBS storage for a single node which provides the durability of 99.99%. Moreover, TiKV organizes 3 Raft replicas on top of that, which may be overkill for durability. To reduce cost, we can introduce a mechanism named "2 Replicas With 1 Log Only" instead of 3 replicas to save 30% storage resources and cut down about 100%(1 core) CPU usage empirically on the cloud. Compared with the original 3 replicas architecture, the "1 Log Only" replica stores raft logs but does not apply it, which still ensures data consistency through the Raft protocol.

## Task Breakdown

- TiKV
  - [x] modify kvproto, add witness field @Connor1996 
    - https://github.com/pingcap/kvproto/pull/928
    - https://github.com/pingcap/kvproto/pull/975
  - [x] Precedent code clean
    - https://github.com/tikv/tikv/pull/13244
    - https://github.com/tikv/tikv/pull/13307
    - https://github.com/tikv/tikv/pull/13377
  - [x] raftstore process to support witness @Connor1996 https://github.com/tikv/tikv/pull/12972
    - [x] forbid write and read for witness
    - [x] reject transfer leader command for witness
    - [x] skip apply write command for witness
    - [x] reject generating snapshot when witness is leader
  - [x] witness skip raft log gc if has lagging peer @ethercflow https://github.com/tikv/tikv/pull/13869
    - [x] add replicated index in CompactLog command https://github.com/pingcap/kvproto/pull/1023
    - [x] fix panic https://github.com/tikv/tikv/pull/14054
  - [x] witness take low priority election @ethercflow https://github.com/tikv/tikv/pull/13491
    - [x] Adjust raft-rs impl to solve compatibility issue https://github.com/tikv/raft-rs/pull/495
  - [x] witness conf change 
    - [x] adaption to snapshot process, witness use empty snap @Connor1996  https://github.com/tikv/tikv/pull/12972
    - [x] kvproto add a new admin command https://github.com/pingcap/kvproto/pull/1004   
    - [x] add switch witness operator @ethercflow https://github.com/tikv/pd/pull/5634
    - [x] support non-witness -> witness @ethercflow https://github.com/tikv/tikv/pull/13491
    - [x] support witness -> non-witness @ethercflow https://github.com/tikv/tikv/pull/13491
      - [x] trace peer's available state on leader side @ethercflow  https://github.com/tikv/tikv/pull/13209
      - [x] refine request snapshot https://github.com/tikv/raft-rs/pull/499
  - [ ] PD wait nonwitness -> witness operator finished to avoid too frequent delete(optional)

- PD
  - [x] Use conf change V2 for all operators @Connor1996  https://github.com/tikv/pd/issues/5407
  - [x] Modify placement rule to support adding witness @ethercflow https://github.com/tikv/pd/pull/5292
    - [ ] Need version control to make sure compatibility during rolling update
  - [x] Show witness count on PD Metrics @Connor1996 https://github.com/tikv/pd/pull/5530
  - [x] Consider witness count for balance region scheduler @ethercflow https://github.com/tikv/pd/pull/5763
  - [x] Transfer leader out when witness is the leader @ethercflow https://github.com/tikv/pd/pull/5639
  - [x] Rule checker promotes the witness to voter when region has down peer @ethercflow https://github.com/tikv/pd/pull/5630
  - [x] Rule checker promotes the witness to voter when one peer is lagging behind a lot @ethercflow https://github.com/tikv/pd/pull/5630
  - [x] Rule checker adds a witness when region has down peer (when witness placement rule is not enabled) @ethercflow https://github.com/tikv/pd/pull/5630
  - [x] Balance leader scheduler filters out witness @ethercflow  https://github.com/tikv/pd/pull/5751
  - [x] Consider merge in merge scheduler @ethercflow https://github.com/tikv/pd/pull/5634
  - [ ] Do not add witness on tiflash @ethercflow 

- TiKV client @ethercflow 
  - [x] Skip the witnesses when follower reads choose the target peer https://github.com/tikv/client-go/pull/633
  - [x] Retry on IsWitness error https://github.com/tikv/client-go/pull/633
    - [x] Add a new error type https://github.com/pingcap/kvproto/pull/1031

- Doc 
  - [ ] RFC
  - [ ] user document https://github.com/pingcap/docs-cn/pull/12628

**Comment by Connor1996** [comment]
> I think we should make a prototype first.

Separate the tasks into two stages, and the first stage is focus on prototype

**Comment by zhangjinpeng1987** [comment]
Is there any conflict with PD's schedulers like hotspot scheduler

**Comment by Connor1996** [comment]
> Is there any conflict with PD's schedulers like hotspot scheduler

will consider witness in hotspot scheduler

**Comment by jterrace** [comment]
Did this end up launching or is it paused?

**Comment by Connor1996** [comment]
@jterrace It's paused
