### ISSUE TITLE
Enhanced queueing for conflicting pessimistic transactions

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#13298]
## Background

Currently, we are adopting a simple but rough implementation for pessimistic lock waiting and waking up. It works just fine in most normal cases, however, there will be problems under workloads that has frequent lock conflicts. When there are many requests trying to acquire the lock on a single key in TiKV:

* The order that the transactions successfully get the lock has too much randomness
* When a pessimistic lock request is woken up after waiting a while in TiKV, it always returns `WriteConflict` to TiDB so that TiDB will retry the statement.
* When many pessimistic lock requests are waiting on the same key in TiKV and the current lock is released, one of the requests will be woken up, and the others will be woken up too after delaying for `wake-up-delay-duration` (which is a configurable value that defaults to 10ms). If the first awakened transaction's retrying request arrives late, the key might already have been locked by another transaction.

This may lead to some problems:

* The latency to acquire the lock might be very unstable, causing high tail latency.
* There might be too many statement-retries that are useless but wastes resources.
* When the problem is severe, it's also possible to cause errors like lock wait timeout and statement retry limit exceeded.

By carefully adjusting `wake-up-delay-duration`, we are actually able to try to make it work well in most scenarios. However, it's very hard to adjust it since it's difficult to predict the effect of changing it. It's even harder if a user who don't understand the internal implementation of TiKV want to tune it. Besides, its a store level config, which means, if a user have more than one workloads that has different characteristics in a single cluster, it's impossible to use different `wake-up-delay-duration` for different workloads.

We expects it would be better to make transactions in such kind of scenarios to execute sequentially, avoiding too much useless statement retries and high tail latency. However, this will be very complicated to implement in our current architecture, especially considering that we needs to guarantee the backward compatibility. We have a complicated design for this problem and it took us much efforts to trying to demonstrate it. We've confirmed that the complicated design is helpful for solving the problem stated above in those kinds of scenarios. However, the stronger queueing behavior in lock waiting introduces higher average latency, or to say, lower QPS. We do have ideas to optimize it further, however, it would make the design much more complicated.

Now we are going to productize the idea. As the first step, we will first implement a subset of the original design: we will enhance the queueing behavior for pessimistic lock requests that involves only one key. This will be helpful for many cases that has frequent lock conflicts on some single rows. And since there's possibly QPS regression, the new behavior will be optional and disabled by default. A user will need to choose to get lower tail latency at the expense of higher average latency if the user needs.

<details>
<summary>Demo branches</summary>

The draft branches for demo can be found at:

* https://github.com/pingcap/tidb/pull/35588
* https://github.com/tikv/client-go
* https://github.com/tikv/tikv/pull/12749

Most part of the final implementation can be ported from these branches, but there will also be some differences.

</details>

## Tasks

- [ ] The RFC / design document
  - RFC for TiKV: https://github.com/tikv/rfcs/pull/100
  - Design doc for TiDB: https://github.com/pingcap/tidb/pull/37518
- [ ] The spec document

- kvproto
    - [x] Protocol change (kvproto) https://github.com/pingcap/kvproto/pull/872
- TiKV
    - [x] Lock waiting queue implementation
        - Each key will have its own waiting queue. In the demo branch, it's put in `Latch`, but later we found hard to store it with an efficient and simple data structure. We will consider store it in the lock table of `ConcurrencyManager` or another separated concurrent hash map.
        - https://github.com/tikv/tikv/pull/13486
        - https://github.com/tikv/tikv/pull/13560
    - [x] Waiter manager & deadlock detector adaption
        - `WaiterManager` no longer have the responsibility to wake up lock requests after the lock is released. Instead, we will need it to be able to index requests by unique tokens. Therefore both its interface and inner data structure need to be updated.
        - https://github.com/tikv/tikv/pull/13447
    - [x] New implementation of storage command `AcquirePessimisticLock`
        - For requests that contains only one key, it can choose to use the new locking behavior: it's allowed to force lock the key even when there's write conflict. It will use the new protocol to return the actual locked ts (the actual lower bound of `for_update_ts`) to the client (TiDB).
        - https://github.com/tikv/tikv/pull/13687
    - [x] Resuming of pessimistic lock requests
        - For pessimistic lock requests that choose to use the new locking behavior, after waiting for another lock, we allow it to continue acquiring the lock after being woken up, instead of returning `WriteConflict` to the client to request a retry.
        - https://github.com/tikv/tikv/pull/13833
        - https://github.com/tikv/tikv/pull/13826
    - [x] Lock wait info update for queueing requests
        - When many requests are queued waiting the same key, and one of them is granted the lock after the previous lock being released, then for the other queueing requests, the transaction they are waiting for is changed. In this case, we need some update operations so that it can perform correct deadlock detection and provide diagnostic information about lock waiting.
- client-go
    - [x] Support aggressive locking behavior
      - https://github.com/tikv/client-go/pull/528
- TiDB
    - [x] Support aggressive locking behavior which can be enabled by system variable
      - https://github.com/pingcap/tidb/pull/35588
- Misc tasks and issues
  - [x] https://github.com/tikv/tikv/pull/13865
  - [x] Telemetry
  - [ ] Confirm compatibility with lazy constraint check in TiDB's pessimistic transaction
  - [ ] Find a proper behavior for the case where insert (should_not_exist) constraint check failure and write conflict occurs together https://github.com/tikv/tikv/issues/14293
  - [ ] In some rare corner cases, for_update_ts collision may cause unexpected pessimistic-rollback https://github.com/pingcap/tidb/issues/41792
  - [ ] In some rare corner cases, replayed pessimistic lock request on a key that lost its pessimistic lock may affect transaction correctness https://github.com/tikv/tikv/issues/14311
- Optional optimizations
    - [ ] Region level waking up after region change (leader or epoch change)
    - [ ] Batch re-detect deadlocks after updating lock wait info
    - [ ] Replace the implementation of `Key` from `Vec<u8>` to something like `Arc<Vec<u8>>` or `Arc<[u8]>` to reduce overhead of cloning keys (it needs to be tested whether it helps)
- Integration tests

**Comment by MyonKeminta** [comment]
Sorry I just notice that this issue is mistakenly closed when merging https://github.com/tikv/tikv/pull/13865
