### ISSUE TITLE
log-backup: tracking issue for unify the infrastructure with other components 

### ISSUE THREAD

**Issue by YuJuncen** [tikv/tikv#13867]
## Development Task
We are using the `etcdv3/etcd-client` library for taking with etcd in PD, because there isn't a mature etcd client implemented with `grpc-rs`. However (sadly!) this requirement brings another ecosystem of infrastructures into the codebase of TiKV:
- [x] `rustls` vs `openssl`
- [ ] `tonic` vs `grpc-rs`
- [ ] `prost!` vs `protobuf-rs`

The most visible problem is we need to compile two different ecosystems: till now not so bad, because `external_storage` has already bring a subtree of `tokio` ecosystem into TiKV.

Things went even worse when we were going to talk about compatibility problems here: for example, a certificate provided for TiKV now must be generic enough to pass the checking both in `openssl` and `rustls`: the set of available certs now shrinks to the intersection of `available_certs_of(RUSTLS)` and `available_certs_of(OPENSSL)`, which is inconsistent and annoying.

We need try to migrate into the existing ecosystem in TiKV for long term.
