### ISSUE TITLE
Tracking issue: Load-based replica read

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#14151]
RFC: https://github.com/tikv/rfcs/pull/105

## Summary

When the read pool load of the leader TiKV is too high, it can reject a coming read request. After that, the client will send the request to follower or learner peers to retry the request in replica-read mode. When a read hotspot occurs, this method allows us to make better use of cluster computing resources.

## Development Tasks

- [ ] Support estimating waiting duration of incoming reading request in TiKV
- [ ] Reject requests whose busy threshold is smaller than the estimated waiting duration
- [ ] Retry reading requests on follower nodes
- [ ] Keep recent TiKV load at client side to reduce useless retries
- [ ] Support returning `applied_index` from the leader in `ServerIsBusy` error to avoid `ReadIndex`
