### ISSUE TITLE
Tracking Issue: In-memory Engine

### ISSUE THREAD

**Issue by SpadeA-Tang** [tikv/tikv#16141]
RFC: https://github.com/tikv/rfcs/pull/111

Summary:
In-memory engine works as a region cache, selectively caching certain regions to enhance read performance.

Tasks:
- [x] Integrate In-memory Engine with TiKV
    - https://github.com/tikv/tikv/pull/16114
    - https://github.com/tikv/tikv/pull/16132
    - https://github.com/tikv/tikv/pull/16383
    - https://github.com/tikv/tikv/issues/17181
- [x] Implement Write 
    - https://github.com/tikv/tikv/issues/16323
    - https://github.com/tikv/tikv/pull/16619
- [x] Implement Read
    - https://github.com/tikv/tikv/pull/16163
    - https://github.com/tikv/tikv/pull/16181
    - https://github.com/tikv/tikv/pull/16193
    - https://github.com/tikv/tikv/pull/16237
- [x] Implement garbage collection
    - https://github.com/tikv/tikv/pull/16238
    - https://github.com/tikv/tikv/pull/16461
- [x] Implement SST ingestion (skipped)
- [ ] Implement Load and Evict
    - https://github.com/tikv/tikv/pull/16500
    - https://github.com/tikv/tikv/issues/16509
- [x] Implement memory controller
    - https://github.com/tikv/tikv/pull/16671
- [x] Auto load and evict
    - https://github.com/tikv/tikv/pull/17023
    - https://github.com/tikv/tikv/pull/17423
    - https://github.com/tikv/tikv/pull/17443
    - https://github.com/tikv/tikv/pull/17450
    - https://github.com/tikv/tikv/pull/17523
    - https://github.com/tikv/tikv/pull/17433
- [x] Implement A High Performant Skiplist
    - https://github.com/tikv/tikv/pull/16652
    - https://github.com/tikv/tikv/issues/17166
- [x] Integration tests framework
    - https://github.com/tikv/tikv/pull/16186
    - https://github.com/tikv/tikv/pull/16474
    - https://github.com/tikv/tikv/pull/16725
- [x] Observability and diagnosibility
    - https://github.com/tikv/tikv/pull/16696
    - https://github.com/tikv/tikv/pull/16735
    - https://github.com/tikv/tikv/pull/16822
    - https://github.com/tikv/tikv/pull/16945
    - https://github.com/tikv/tikv/pull/16971
    - https://github.com/tikv/tikv/pull/16997
    - https://github.com/tikv/tikv/pull/17160
    - https://github.com/tikv/tikv/pull/17161
    - https://github.com/tikv/tikv/pull/17321
- [ ] Cross check
    - https://github.com/tikv/tikv/pull/17241
    - https://github.com/tikv/tikv/pull/17588

## Enhancement
- [x] https://github.com/tikv/tikv/issues/17276

## Bugs

- [x] https://github.com/tikv/tikv/issues/16994
- [x] https://github.com/tikv/tikv/issues/17074
- [x] https://github.com/tikv/tikv/issues/17252
- [x] https://github.com/tikv/tikv/issues/17060
- [ ] https://github.com/tikv/tikv/issues/17018
- [ ] https://github.com/tikv/tikv/issues/16947
- [x] https://github.com/tikv/tikv/issues/17079
- [x] https://github.com/tikv/tikv/issues/17082
- [x] https://github.com/tikv/tikv/issues/17100
- [x] https://github.com/tikv/tikv/issues/17103
- [x] https://github.com/tikv/tikv/issues/17104
- [x] https://github.com/tikv/tikv/issues/17106
- [x] https://github.com/tikv/tikv/issues/17114
- [x] https://github.com/tikv/tikv/issues/17123
- [x] https://github.com/tikv/tikv/issues/17131
- [x] https://github.com/tikv/tikv/issues/17127
- [x] https://github.com/tikv/tikv/issues/17139
- [x] https://github.com/tikv/tikv/issues/17140
- [x] https://github.com/tikv/tikv/issues/17147
- [ ] https://github.com/tikv/tikv/issues/17148
- [x] https://github.com/tikv/tikv/issues/17163
- [x] https://github.com/tikv/tikv/issues/17153
- [x] https://github.com/tikv/tikv/issues/17182
- [x] https://github.com/tikv/tikv/issues/16966
- [ ] https://github.com/tikv/tikv/issues/17243
- [ ] https://github.com/tikv/tikv/issues/17216
- [ ] https://github.com/tikv/tikv/issues/17053
- [x] https://github.com/tikv/tikv/issues/17245
- [x] https://github.com/tikv/tikv/issues/17259
- [x] https://github.com/tikv/tikv/issues/17260
- [x] https://github.com/tikv/tikv/issues/17282
- [x] https://github.com/tikv/tikv/issues/17403
- [x] https://github.com/tikv/tikv/issues/17405
- [x] https://github.com/tikv/tikv/issues/17456
- [x] https://github.com/tikv/tikv/issues/17483
- [x] https://github.com/tikv/tikv/issues/17484
- [x] https://github.com/tikv/tikv/issues/17487
- [x] https://github.com/tikv/tikv/issues/17493
- [x] https://github.com/tikv/tikv/issues/17548
- [x] https://github.com/tikv/tikv/issues/17561
- [x] https://github.com/tikv/tikv/issues/17562
- [x] https://github.com/tikv/tikv/issues/17592
- [x] https://github.com/tikv/tikv/issues/17644
- [ ] https://github.com/tikv/tikv/issues/17645

## Enhancements

- [x] https://github.com/tikv/tikv/issues/17626
- [x] https://github.com/tikv/tikv/issues/17627
- [ ] https://github.com/tikv/tikv/issues/17628
