### ISSUE TITLE
TiKV txn scheduler may cause OOM when raftstore runs slow

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#16234]
## Bug Report

In an internal test that injects IO fault and stops write completely, we find TiKV memory keeps growing and OOM eventually. 
After investigation, we find most of the memory is consumed by `check_secondary_locks` RPCs, they pile up on txn latches.

![image](https://github.com/tikv/tikv/assets/2150711/2f747d23-2423-481d-a6ab-e50d11c0367d)

![image](https://github.com/tikv/tikv/assets/2150711/4f805c23-dd53-4fba-870d-c33b835eff78)
(`check_secondary_locks` tasks are all in new stages, which means they are blocked by latch.)

To fix the OOM we should:
- [x] limit the amount of memory of requests that txn latch can hold. [#16473](https://github.com/tikv/tikv/pull/16473)
- [x] limit the amount of memory of pending/running task on scheduler worker pool. [#16473](https://github.com/tikv/tikv/pull/16473)
- [ ] limit the amount of memory of pending/running tasks on scheduler read pool.
- [ ] limit the amount of memory of pending/running tasks on coprocessor read pool. See https://github.com/tikv/tikv/issues/16653

Cc https://github.com/tikv/tikv/issues/13731
Cc https://github.com/tikv/tikv/issues/15701
Cc #2508

### Steps to reproduce

Inject IO fault and pause write.

### What did you expect?

No OOM.

### What did happened?

OOM.

**Comment by cfzjywxk** [comment]
This was also found in a customer's production environemnt before https://github.com/tikv/tikv/issues/14838.  At that time, the focus was mainly on metrics and slow responses rather than memory. In fact, the root causes of these issues all stem from:
1. Commands that have timed out cannot be canceled in a timely manner and continue to hold latches.
2. Commands in a latch wait state, although they currently respond with a deadline error (https://github.com/tikv/tikv/pull/10771), the related tasks still persist in the queue until they can acquire the latch to wake up or execute them, and then they can be cleaned up because of timeout check.
3. For operations received by the KV client due to being busy, resulting in a deadline error, it is necessary to control the backoff and retry frequency to reduce the possibility of accumulation.

Perhaps, we may also need a similar mechanism like https://github.com/tikv/tikv/issues/14151 to avoid sending too many commands to already queued tikv nodes to make it worse and occupy lots of memory.

**Comment by overvenus** [comment]
Agree, most OOM issues in scheduler eventually boil down to some unknown timeout or retry bugs. The solution (memory quota) proposed here is more like the last resort to prevent OOM.
