### ISSUE TITLE
Tracking issue: pipelined DML, stage 1

### ISSUE THREAD

**Issue by ekexium** [tikv/tikv#16291]
~~RFC: tikv/rfcs#109~~
TiDB Tracking issue https://github.com/pingcap/tidb/issues/50215
Design doc https://github.com/pingcap/tidb/pull/50219
## Development Task
- TiKV
  - https://github.com/tikv/tikv/pull/16364
  - https://github.com/tikv/tikv/pull/16544
  - https://github.com/tikv/tikv/pull/16612
  - https://github.com/tikv/tikv/pull/16613
  - https://github.com/tikv/tikv/pull/16646
  - https://github.com/tikv/tikv/pull/16663
  - [ ] union batch get
- kvproto
  - https://github.com/pingcap/kvproto/pull/1218
  - https://github.com/pingcap/kvproto/pull/1225
- [ ] client-go
  - https://github.com/tikv/client-go/pull/1114
  - https://github.com/tikv/client-go/pull/1205
  - https://github.com/tikv/client-go/pull/1212
  - https://github.com/tikv/client-go/pull/1224
  - https://github.com/tikv/client-go/pull/1230
  - https://github.com/tikv/client-go/pull/1233
- TiDB
  - https://github.com/pingcap/tidb/pull/50389
  - https://github.com/pingcap/tidb/issues/51625
  - https://github.com/pingcap/tidb/issues/51629
- Compatibility
  - [ ] BR
  - CDC: won't be compatible in stage 1
- Optimization
  - [ ] Resolve locks using txn cache
  - [ ] Spill keys to disk in client-go
  - [ ] Record key range for each index
  - [ ] Cache min_commit_ts in transaction cache
