### ISSUE TITLE
Tracking issue for compatibility between ingesting SST and resolved TS / TiCDC / log backup

### ISSUE THREAD

**Issue by YuJuncen** [tikv/tikv#16533]
## Development Task

As a "contextual" raft command, for now, both *TiCDC and log backup* cannot replicate the content loaded by ingesting SST.
We need make them compatible.

- [ ] Make log backup be able to backup ingested data. @YuJuncen 
  - It requires the start TS of the default CF while backing up write CF.
- [ ] Make TiCDC be able to replicate ingested data. <ins>*Not scheduled yet*</ins>

Also, ingesting directly write data without run Percolator transaction. So *resolved TS* is invalid when we are ingesting SSTs. 

- [ ] Make resolved TS compatible with ingesting by the `notify` RPC family.
  - [ ] Implement the `notify` RPC family. @overvenus 
    - [x] https://github.com/tikv/tikv/pull/16586
    - [x] https://github.com/tikv/tikv/pull/16594
    - [ ] https://github.com/pingcap/kvproto/pull/1229
  - [ ] tidb-lightning adapt the `notify` RPC family. @lance6716 
    - [ ] https://github.com/pingcap/tidb/issues/51312
    - [ ] #16582

There are some *performance issues* we may encounter:
- [ ] Frequently importing small tables may break the backup. @Benjamin2037
  - [ ] Hide tables during importing.
- [ ] Leader transform (exactly when doing rolling restart may generate tons of scan result. <ins>*Not scheduled yet*</ins>

**Comment by BornChanger** [comment]
please also add the tasks related to performance, including filtering and toleration to rolling restart.

**Comment by YuJuncen** [comment]
This features is suspended now.
