### ISSUE TITLE
Algorithm-based eviction and loading using region stats manager

### ISSUE THREAD

**Issue by afeinberg** [tikv/tikv#16567]
## Algorithm-based eviction and loading using region stats manager

Parent issue: #16417 

## Tasks

- [ ] Periodic task to determine and cache top N regions
- [ ] Periodic task to evict regions no longer in the top N
- [ ] Interaction with apply thread
