### ISSUE TITLE
tracking issue for implementing `compact-log-backup` in `tikv-ctl`

### ISSUE THREAD

**Issue by YuJuncen** [tikv/tikv#17283]
## Development Task

Can be merge without kvproto change:

- [ ] Add interfaces needed by `compact-log-backup`.

Waiting kvproto changes: 

- [ ] Add CRC64 for logs generated by log backup.
- [ ] Implement compacting log backup base library.
- [ ] Add compacting log backup to `tikv-ctl`.

**Comment by BornChanger** [comment]
please also add the task to adapt to object lock etc.
