### ISSUE TITLE
coprocessor/expression: push down scalar functions

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#3275]
# Update

The content in this issue is outdated. Please refer to https://github.com/tikv/tikv/issues/5751 for a latest list.

<details>
  <summary>Click to expand the original content</summary>

## Feature Request

In coprocessor, for reading operations, some functions have been pushed down to tikv  to make the computation distribute into each region. For example, when TiDB receives a SQL query like

```sql
select sum(col1+col2) from table1
```

TiDB would push down the computation `sum(col1+col2)` to each region (TiKV) of the table.

Now there are lots of functions need to been pushed down into TiKV, some have been implemented already while the rest may need your help.

Here is the list of functions to been pushed down, you may pick one to make a pull request:

### Casting

- [X] CastIntAsInt
- [X] CastIntAsReal
- [X] CastIntAsString
- [X] CastIntAsDecimal
- [X] CastIntAsTime
- [X] CastIntAsDuration
- [X] CastIntAsJson
- [X] CastRealAsInt
- [X] CastRealAsReal
- [X] CastRealAsString
- [X] CastRealAsDecimal
- [X] CastRealAsTime
- [X] CastRealAsDuration
- [X] CastRealAsJson
- [X] CastDecimalAsInt
- [X] CastDecimalAsReal
- [X] CastDecimalAsString
- [X] CastDecimalAsDecimal
- [X] CastDecimalAsTime
- [X] CastDecimalAsDuration
- [X] CastDecimalAsJson
- [X] CastStringAsInt
- [X] CastStringAsReal
- [X] CastStringAsString
- [X] CastStringAsDecimal
- [X] CastStringAsTime
- [X] CastStringAsDuration
- [X] CastStringAsJson
- [X] CastTimeAsInt
- [X] CastTimeAsReal
- [X] CastTimeAsString
- [X] CastTimeAsDecimal
- [X] CastTimeAsTime
- [X] CastTimeAsDuration
- [X] CastTimeAsJson
- [X] CastDurationAsInt
- [X] CastDurationAsReal
- [X] CastDurationAsString
- [X] CastDurationAsDecimal
- [X] CastDurationAsTime
- [X] CastDurationAsDuration
- [X] CastDurationAsJson
- [X] CastJsonAsInt
- [X] CastJsonAsReal
- [X] CastJsonAsString
- [X] CastJsonAsDecimal
- [X] CastJsonAsTime
- [X] CastJsonAsDuration
- [X] CastJsonAsJson

### Compare

- [X] CoalesceInt
- [X] CoalesceReal
- [X] CoalesceDecimal
- [X] CoalesceString
- [X] CoalesceTime
- [X] CoalesceDuration
- [X] CoalesceJson
- [X] LTInt
- [X] LTReal
- [X] LTDecimal
- [X] LTString
- [X] LTTime
- [X] LTDuration
- [X] LTJson
- [X] LEInt
- [X] LEReal
- [X] LEDecimal
- [X] LEString
- [X] LETime
- [X] LEDuration
- [X] LEJson
- [X] GTInt
- [X] GTReal
- [X] GTDecimal
- [X] GTString
- [X] GTTime
- [X] GTDuration
- [X] GTJson
- [X] GreatestInt @bb7133  #3113
- [X] GreatestReal @bb7133  #3113
- [X] GreatestDecimal @bb7133  #3113
- [X] GreatestString @bb7133  #3113
- [X] GreatestTime @bb7133  #3113
- [X] LeastInt @bb7133  #3113
- [X] LeastReal @bb7133  #3113
- [X] LeastDecimal @bb7133  #3113
- [X] LeastString @bb7133  #3113
- [X] LeastTime @bb7133  #3113
- [X] IntervalInt @bb7133 #3330
- [X] IntervalReal @bb7133 #3330
- [X] GEInt
- [X] GEReal
- [X] GEDecimal
- [X] GEString
- [X] GETime
- [X] GEDuration
- [X] GEJson
- [X] EQInt
- [X] EQReal
- [X] EQDecimal
- [X] EQString
- [X] EQTime
- [X] EQDuration
- [X] EQJson
- [X] NEInt
- [X] NEReal
- [X] NEDecimal
- [X] NEString
- [X] NETime
- [X] NEDuration
- [X] NEJson
- [X] NullEQInt
- [X] NullEQReal
- [X] NullEQDecimal
- [X] NullEQString
- [X] NullEQTime
- [X] NullEQDuration
- [X] NullEQJson

### Arithmetic

- [X] PlusReal
- [X] PlusDecimal
- [X] PlusInt
- [X] MinusReal
- [X] MinusDecimal
- [X] MinusInt
- [X] MultiplyReal
- [X] MultiplyDecimal
- [X] MultiplyInt
- [X] MultiplyIntUnsigned
- [X] DivideReal
- [X] DivideDecimal
- [X] IntDivideInt @bb7133 #3030
- [X] IntDivideDecimal @bb7133 #3030
- [X] ModReal @bb7133 #3030
- [X] ModDecimal @bb7133 #3030
- [X] ModInt @bb7133 #3030

### Math

- [X] AbsInt
- [X] AbsUInt
- [X] AbsReal
- [X] AbsDecimal
- [X] CeilIntToDec
- [X] CeilIntToInt
- [X] CeilDecToInt
- [X] CeilDecToDec
- [X] CeilReal
- [X] FloorIntToDec
- [X] FloorIntToInt
- [X] FloorDecToInt
- [X] FloorDecToDec
- [X] FloorReal
- [X] RoundReal @colinback #3621
- [X] RoundInt @intellild #3395
- [X] RoundDec @colinback #3621
- [X] RoundWithFracReal @colinback #3621
- [X] RoundWithFracInt @colinback #3621
- [X] RoundWithFracDec @colinback #3621
- [X] Log1Arg @sllt #3603
- [X] Log2Args @sllt #3603
- [X] Log2 @sllt #3379
- [X] Log10 @sllt #3379
- [X] Rand @xiangyuf #3415
- [X] RandWithSeed @xiangyuf #3415
- [X] Pow @smallyard #3475
- [X] Conv @niedhui #3691
- [X] CRC32 @TennyZhuang #3374
- [X] Sign @Observer42 #3518
- [X] Sqrt @xiangyuf #3476
- [X] Acos @malc0lm #3482
- [X] Asin @malc0lm #3482
- [X] Atan1Arg @Observer42 #3520
- [X] Atan2Args @Observer42 #3520
- [X] Cos @vkorenev #3410
- [X] Cot @mtunique #3543
- [X] Degrees @mtunique #3543
- [X] Exp @niedhui #3686
- [X] PI @sweetIan #3382
- [X] Radians @niedhui #3683
- [X] Sin @liufuyang #3406
- [X] Tan @arosspope #3456
- [X] TruncateInt @niedhui #3532
- [X] TruncateReal @niedhui #3633
- [X] TruncateDecimal @niedhui #3637

### Operator

- [X] LogicalAnd
- [X] LogicalOr
- [X] LogicalXor
- [X] UnaryNot
- [X] UnaryMinusInt
- [X] UnaryMinusReal
- [X] UnaryMinusDecimal
- [X] DecimalIsNull
- [X] DurationIsNull
- [X] RealIsNull
- [X] StringIsNull
- [X] TimeIsNull
- [X] IntIsNull
- [X] JsonIsNull
- [X] BitAndSig
- [X] BitOrSig
- [X] BitXorSig
- [X] BitNegSig
- [X] IntIsTrue
- [X] RealIsTrue
- [X] DecimalIsTrue
- [X] IntIsFalse
- [X] RealIsFalse
- [X] DecimalIsFalse
- [X] LeftShift @spongedu #3391
- [X] RightShift @spongedu #3391

### Control

- [X] IfNullInt
- [X] IfNullReal
- [X] IfNullDecimal
- [X] IfNullString
- [X] IfNullTime
- [X] IfNullDuration
- [X] IfInt
- [X] IfReal
- [X] IfDecimal
- [X] IfString
- [X] IfTime
- [X] IfDuration
- [X] IfNullJson
- [X] IfJson
- [X] CaseWhenInt
- [X] CaseWhenReal
- [X] CaseWhenDecimal
- [X] CaseWhenString
- [X] CaseWhenTime
- [X] CaseWhenDuration
- [X] CaseWhenJson

### Encryption

- [ ] AesDecrypt
- [ ] AesEncrypt
- [X] Compress @niedhui #3856
- [X] MD5 @Hijiao #3554
- [ ] Password
- [ ] RandomBytes
- [X] SHA1 @haoxiang47 #3612
- [X] SHA2 @spongedu #3649
- [X] Uncompress @niedhui #3856
- [X] UncompressedLength @niedhui #3856

### Info

- [ ] ~Database~
- [ ] ~FoundRows~
- [ ] ~CurrentUser~
- [ ] ~User~
- [ ] ~ConnectionID~
- [ ] ~LastInsertID~
- [ ] ~LastInsertIDWithID~
- [ ] ~Version~
- [ ] ~TiDBVersion~
- [ ] ~RowCount~

### Miscellaneous

- [ ] Sleep
- [ ] Lock
- [ ] ReleaseLock
- [ ] DecimalAnyValue
- [ ] DurationAnyValue
- [ ] IntAnyValue
- [ ] JSONAnyValue
- [ ] RealAnyValue
- [ ] StringAnyValue
- [ ] TimeAnyValue
- [X] InetAton @rleungx #3659
- [X] InetNtoa @rleungx #3659
- [X] Inet6Aton @sweetIan #3480
- [X] Inet6Ntoa @sweetIan #3519
- [X] IsIPv4 @opensourcegeek #3460
- [ ] IsIPv4Compat
- [ ] IsIPv4Mapped
- [X] IsIPv6 @opensourcegeek #3479
- [ ] UUID

### Like

- [X] LikeSig
- [X] RegexpBinarySig @bb7133  #3196
- [X] RegexpSig @bb7133  #3196

### JSON

- [X] JsonExtractSig
- [X] JsonUnquoteSig
- [X] JsonTypeSig
- [X] JsonSetSig
- [X] JsonInsertSig
- [X] JsonReplaceSig
- [X] JsonRemoveSig
- [X] JsonMergeSig
- [X] JsonObjectSig
- [X] JsonArraySig

### Time

- [X] DateFormatSig
- [ ] DateLiteral
- [x] DateDiff @edwardpku #3937
- [ ] NullTimeDiff
- [ ] TimeStringTimeDiff
- [ ] DurationStringTimeDiff
- [ ] DurationDurationTimeDiff
- [ ] StringTimeTimeDiff
- [ ] StringDurationTimeDiff
- [ ] StringStringTimeDiff
- [ ] TimeTimeTimeDiff
- [X] Date @hawkingrei #3428
- [X] Hour @koushiro #3753
- [X] Minute @koushiro #3753
- [X] Second @koushiro #3753
- [X] MicroSecond @koushiro #3753
- [X] Month @chux0519 #3569
- [X] MonthName @koushiro #3735
- [ ] NowWithArg
- [ ] NowWithoutArg
- [X] DayName @koushiro #3774
- [X] DayOfMonth @koushiro #3774
- [X] DayOfWeek @koushiro #3774
- [X] DayOfYear @koushiro #3774
- [X] WeekWithMode @AbnerZheng #3857
- [X] WeekWithoutMode @AbnerZheng #3861
- [X] WeekDay @koushiro #3871
- [X] WeekOfYear @koushiro #3871
- [X] Year @Kingwl #3622
- [x] YearWeekWithMode @AbnerDBFan #3876
- [x] YearWeekWithoutMode @AbnerDBFan #3876
- [ ] GetFormat
- [ ] SysDateWithFsp
- [ ] SysDateWithoutFsp
- [ ] ~CurrentDate~
- [ ] CurrentTime0Arg
- [ ] CurrentTime1Arg
- [ ] Time
- [ ] TimeLiteral
- [ ] UTCDate
- [ ] UTCTimestampWithArg
- [ ] UTCTimestampWithoutArg
- [x] AddDatetimeAndDuration @koushiro #3899
- [x] AddDatetimeAndString @koushiro #3899
- [x] AddTimeDateTimeNull @koushiro #4063
- [ ] AddStringAndDuration
- [ ] AddStringAndString
- [ ] AddTimeStringNull
- [x] AddDurationAndDuration @GinYM #3984 
- [x] AddDurationAndString @DCjanus #4010 
- [x] AddTimeDurationNull @koushiro #4063 
- [ ] AddDateAndDuration
- [ ] AddDateAndString
- [ ] SubDatetimeAndDuration
- [ ] SubDatetimeAndString
- [ ] SubTimeDateTimeNull
- [ ] SubStringAndDuration
- [ ] SubStringAndString
- [ ] SubTimeStringNull
- [ ] SubDurationAndDuration
- [ ] SubDurationAndString
- [ ] SubTimeDurationNull
- [ ] SubDateAndDuration
- [ ] SubDateAndString
- [ ] UnixTimestampCurrent
- [ ] UnixTimestampInt
- [ ] UnixTimestampDec
- [ ] ConvertTz
- [ ] MakeDate
- [ ] MakeTime
- [ ] PeriodAdd
- [ ] PeriodDiff
- [ ] Quarter
- [ ] SecToTime
- [ ] TimeToSec
- [ ] TimestampAdd
- [x] ToDays @GinYM #3978 
- [ ] ToSeconds
- [ ] UTCTimeWithArg
- [ ] UTCTimeWithoutArg
- [ ] Timestamp1Arg
- [ ] Timestamp2Args
- [ ] TimestampLiteral
- [X] LastDay @WPH95 #3556
- [ ] StrToDateDate
- [ ] StrToDateDatetime
- [ ] StrToDateDuration
- [ ] FromUnixTime1Arg
- [ ] FromUnixTime2Arg
- [ ] ExtractDatetime
- [ ] ExtractDuration
- [ ] AddDateStringString
- [ ] AddDateStringInt
- [ ] AddDateStringDecimal
- [ ] AddDateIntString
- [ ] AddDateIntInt
- [ ] AddDateDatetimeString
- [ ] AddDateDatetimeInt
- [ ] SubDateStringString
- [ ] SubDateStringInt
- [ ] SubDateStringDecimal
- [ ] SubDateIntString
- [ ] SubDateIntInt
- [ ] SubDateDatetimeString
- [ ] SubDateDatetimeInt
- [ ] FromDays
- [ ] TimeFormat
- [ ] TimestampDiff

### String functions

- [X] BitLength @spongedu #3376
- [X] Bin @spongedu #3397
- [X] ASCII @spongedu #3436
- [ ] Char
- [X] CharLength @spongedu #3461
- [X] Concat @crazycs520 #3654
- [x] ConcatWS @kg88 #3818
- [ ] Convert
- [X] Elt @spongedu #3555
- [ ] ExportSet3Arg
- [ ] ExportSet4Arg
- [ ] ExportSet5Arg
- [x] FieldInt @manifoldQAQ #4007
- [x] FieldReal @manifoldQAQ #4007
- [x] FieldString @manifoldQAQ #4007
- [ ] FindInSet
- [ ] Format
- [ ] FormatWithLocale
- [X] FromBase64 @niedhui #3716
- [X] HexIntArg @sweetIan #3478
- [X] HexStrArg @sweetIan #3478
- [ ] Insert
- [ ] InsertBinary
- [ ] Instr
- [ ] InstrBinary
- [x] LTrim @spongedu #3400
- [X] Left @spongedu #3413
- [x] LeftBinary
- [X] Length @spongedu #3376
- [x] Locate2Args @gaodayue #4016
- [x] Locate3Args @gaodayue #4016
- [x] LocateBinary2Args @gaodayue #4016
- [x] LocateBinary3Args @gaodayue #4016
- [X] Lower @spongedu #3433
- [x] Lpad @niedhui #3943 
- [x] LpadBinary @niedhui #3943 
- [ ] MakeSet
- [ ] OctInt @yjhmelody #3605
- [ ] OctString
- [ ] Ord
- [ ] Quote
- [X] RTrim @spongedu #3400
- [ ] Repeat
- [x] Replace @lerencao #4360 
- [X] Reverse @spongedu #3435
- [X] ReverseBinary @spongedu #3435
- [X] Right @rleungx #3653
- [x] RightBinary @niedhui #3982
- [x] Rpad @niedhui #3914
- [x] RpadBinary @niedhui #3914
- [X] Space @niedhui #3841
- [X] Strcmp @niedhui #3879
- [X] Substring2Args @niedhui #3472
- [X] Substring3Args @niedhui #3472
- [X] SubstringBinary2Args @niedhui #3813
- [X] SubstringBinary3Args @niedhui #3813
- [X] SubstringIndex @niedhui #3717
- [X] ToBase64 @niedhui #3716
- [X] Trim1Arg @niedhui #3698
- [X] Trim2Args @niedhui #3698
- [X] Trim3Args @niedhui #3698
- [X] UnHex @sweetIan #3469
- [X] Upper @spongedu #3433

### Other

- [X] BitCount @spongedu #3394
- [ ] GetParamString
- [ ] GetVar
- [ ] RowSig
- [ ] SetVar
- [ ] ValuesDecimal
- [ ] ValuesDuration
- [ ] ValuesInt
- [ ] ValuesJSON
- [ ] ValuesReal
- [ ] ValuesString
- [ ] ValuesTime
- [X] InInt @winoros #2411
- [X] InReal @winoros #2411
- [X] InDecimal @winoros #2411
- [X] InString @winoros #2411
- [X] InTime @winoros #2411
- [X] InDuration @winoros #2411
- [X] InJson @winoros #2411

</details>

**Comment by bb7133** [comment]
Regexp/RegexpBinary added: https://github.com/pingcap/tikv/pull/3196

**Comment by laidahe** [comment]
i want to implement math/RouldReal, OK?

**Comment by AndreMouche** [comment]
Of course you can, enjoy yourself　@laidahe

**Comment by laidahe** [comment]
Is there any guide on math/RoundReal? @AndreMouche

**Comment by breeswish** [comment]
@AndreMouche Seems that we need to correct our typo first: RouldReal -> RoundReal

**Comment by spongedu** [comment]
@AndreMouche @breeswish  I think we'd better not push those builtin functions that don't use column data ( e.g:  `UUID`, `PI`) down to `coprocessor` because:
1. they don't make use of data in TiKV 
2. they aggravate network traffic between TiKV nodes and TiDB nodes

**Comment by yangwenmai** [comment]
I want to implement info:

- [x] Database
- [x] FoundRows
- [x] CurrentUser
- [x] User
- [x] ConnectionID
- [x] LastInsertID
- [x] LastInsertIDWithID
- [x] Version
- [x] TiDBVersion
- [x] RowCount

One by one, or implement the submitted together?

**Comment by spongedu** [comment]
@breeswish  yes, I think there's no need push down these down to coprocessor....

**Comment by colinback** [comment]
I'm going to do RoundXXX in Math: 
- [ ] RouldReal
- [ ] RoundInt
- [ ] RoundDec
- [ ] RoundWithFracReal
- [ ] RoundWithFracInt
- [ ] RoundWithFracDec

**Comment by breeswish** [comment]
@yangwenmai Thanks for your interest. As stated above, these functions seems to be not suitable for push down and we will remove it from the list. Please choice other functions :)

**Comment by breeswish** [comment]
@colinback @yangwenmai Also please keep PR small so that it would be faster for review, for example, 1 function per PR.

**Comment by breeswish** [comment]
@spongedu I have an idea. How about expressions like  col = PI() ? In this case, filtered data will be responded from coprocessor instead of full data.

**Comment by spongedu** [comment]
@breeswish In this case, the planner will resolve `PI` and make it a constant.  I think in some cases the query would be changed to an index scan, that may be faster.

```sql
tidb> explain select * from t where a = PI();
+---------------------+----------+------+------------------------------------------------------------+
| id                  | count    | task | operator info                                              |
+---------------------+----------+------+------------------------------------------------------------+
| TableReader_7       | 0.00     | root | data:Selection_6                                           |
| └─Selection_6       | 0.00     | cop  | eq(test.t.a, 3.141592653589793)                            |
|   └─TableScan_5     | 10000.00 | cop  | table:t, range:[-inf,+inf], keep order:false, stats:pseudo |
+---------------------+----------+------+------------------------------------------------------------+
3 rows in set (0.01 sec)
```

but there may be this case: `... where col = UUID() `, though the usage is rare...  If these builtins are used this way, they should be processed in coprocessor..  We can left it to planner whether to push down these builtins.  On the other hand, I think builtins in `builtin_info.go` would not be used in predicates.  For example, `TiDBVersion` should be bound to TiDB and not push down to storage layer..

**Comment by TennyZhuang** [comment]
It seems that there is no session info in eval_context, so it's very difficult to push down the expressions in info

**Comment by opensourcegeek** [comment]
I'd like to take a stab at

- [ ] IsIPv4

first and if I get my head around the code, I'd like to implement the following ones as well if that's OK?

- [ ] InetAton
- [ ] InetNtoa

**Comment by AndreMouche** [comment]
I'm not sure, they( e.g: UUID, PI) may be used as constant @XuHuaiyu @zz-jason ? I guess @breeswish @spongedu

**Comment by zz-jason** [comment]
@AndreMouche 
`UUID` can not be folded as a constant in plan generation phase, I think we still need to implement this function in TiKV.

As for `PI`, it can be folded as a constant, I think it's ok to not implement this function in TiKV.

**Comment by vkorenev** [comment]
I'd like to implement **sin** and **cos**.

**Comment by opensourcegeek** [comment]
@AndreMouche @zz-jason thanks, so do you think IsIpV4 and other IP addressing related functions need not be implemented in TiKV?

**Comment by zz-jason** [comment]
@opensourcegeek No, these functions need to be implemented in TiKV as well.

**Comment by spongedu** [comment]
@zz-jason @AndreMouche  It seems that only those builtins in `builtin_info.go` need not be implemented in TiKV.

**Comment by zz-jason** [comment]
@spongedu Yes, I've already removed these functions in the list by a strikethrough.

**Comment by zz-jason** [comment]
@spongedu And also some date functions can be folded to a constant and don't need to be implemented in TiKV, for example, `CurrentDate`, `now()`.

**Comment by zz-jason** [comment]
@spongedu I remember there is a MySQL document about what functions can be constant-folded in the planner phase. 

In TiDB, only these functions can not be folded: https://github.com/pingcap/tidb/blob/master/expression/function_traits.go#L42

**Comment by opensourcegeek** [comment]
@zz-jason @AndreMouche in that case would you be fine with me to start with IsIpV4 impl?

**Comment by zz-jason** [comment]
@opensourcegeek Sure! 😄

**Comment by opensourcegeek** [comment]
@zz-jason great - are you creating separate issues for each function and assigning to folks trying to implement them (as it says in the [post](https://pingcap.com/blog/adding-built-in-functions-to-tikv/)?)

**Comment by liufuyang** [comment]
@AndreMouche or someone is in charge here, can I try the math.sin() first to see whether I can do i? :thinking:

**Comment by vkorenev** [comment]
@liufuyang https://github.com/tikv/tikv/issues/3275#issuecomment-410605573

**Comment by zz-jason** [comment]
@opensourcegeek Sorry for the late reply, you can pick an unchecked item in the function list above, and make a comment in this issue to let other people know that you are working on it to avoid duplicate work. We'll modify the check list once we see your comment.

@AndreMouche @breeswish How do you think?

**Comment by xiangyuf** [comment]
hi all, is there anyway to rerun the CircleCI in my pull request https://github.com/tikv/tikv/pull/3408 ? The current ci test shows my change failed on raftstore_cases::test_node_merge_brain_split, but my change is not related with this module at all.

**Comment by liufuyang** [comment]
@vkorenev sorry I didn't saw your comments earlier. Do you already have a working branch of both sin or cos? Or perhaps you can do the Cos one. I only did sin :)

**Comment by xiangyuf** [comment]
Rand, RandWithSeed implemented.

**Comment by hawkingrei** [comment]
#3428

**Comment by malc0lm** [comment]
Hi all, I will implement Acos and Asin.

**Comment by chux0519** [comment]
Hi guys, I will impl time/Month

**Comment by niedhui** [comment]
Hi , I will impl math/	TruncateInt, TruncateReal, TruncateDecimal

**Comment by xiangyuf** [comment]
anyone help to review my pr? #3415

**Comment by colinback** [comment]
Anyone else has following problem of ci/circleci: test in PR?
```
$ #!/bin/bash -eo pipefail
env SKIP_TESTS=true make trace_test
env CI=true SKIP_FORMAT_CHECK=true FAIL_POINT=1 /home/circleci/tikv-ci/ci-build/test.sh
make[1]: Entering directory `/home/circleci/tikv-ci'
info: downloading component 'clippy-preview'
info: installing component 'clippy-preview'
    Checking tikv v2.1.0-beta (file:///home/circleci/tikv-ci)
    Checking test_raftstore v0.0.1 (file:///home/circleci/tikv-ci/components/test_raftstore)
    Checking test_util v0.0.1 (file:///home/circleci/tikv-ci/components/test_util)
    Checking tikv_fuzz v0.0.1 (file:///home/circleci/tikv-ci/fuzz)
    Checking test_storage v0.0.1 (file:///home/circleci/tikv-ci/components/test_storage)
error[E0425]: cannot find value `FLAG_IGNORE_TRUNCATE` in this scope
   --> src/coprocessor/dag/expr/builtin_math.rs:383:65
    |
383 |         let mut ctx = EvalContext::new(Arc::new(EvalConfig::new(FLAG_IGNORE_TRUNCATE).unwrap()));
    |                                                                 ^^^^^^^^^^^^^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
    |
175 |     use coprocessor::dag::expr::ctx::FLAG_IGNORE_TRUNCATE;
    |

error[E0061]: this function takes 0 parameters but 1 parameter was supplied
   --> src/coprocessor/dag/expr/builtin_math.rs:383:49
    |
383 |         let mut ctx = EvalContext::new(Arc::new(EvalConfig::new(FLAG_IGNORE_TRUNCATE).unwrap()));
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 0 parameters
    | 
   ::: src/coprocessor/dag/expr/ctx.rs:77:5
    |
77  |     pub fn new() -> EvalConfig {
    |     -------------------------- defined here

error[E0599]: no method named `unwrap` found for type `coprocessor::dag::expr::ctx::EvalConfig` in the current scope
   --> src/coprocessor/dag/expr/builtin_math.rs:383:87
    |
383 |         let mut ctx = EvalContext::new(Arc::new(EvalConfig::new(FLAG_IGNORE_TRUNCATE).unwrap()));
    |                                                                                       ^^^^^^
    | 
   ::: src/coprocessor/dag/expr/ctx.rs:53:1
    |
53  | pub struct EvalConfig {
    | --------------------- method `unwrap` not found for this

error: aborting due to 3 previous errors

Some errors occurred: E0061, E0425, E0599.
For more information about an error, try `rustc --explain E0061`.
error: Could not compile `tikv`.

To learn more, run the command again with --verbose.
make[1]: *** [clippy] Error 101
make[1]: Leaving directory `/home/circleci/tikv-ci'
please fix the errors!!!
make: *** [trace_test] Error 1
Exited with code 2
```

However I 'make test' runs OK on my desktop. No idea about this.

**Comment by hawkingrei** [comment]
Data has been completed. #3428

**Comment by mtunique** [comment]
Hi, I will impl `Cot` and `Degrees`.

**Comment by WPH95** [comment]
Hi i will impl LastDay

**Comment by yjhmelody** [comment]
Hi, I will impl OctInt.

**Comment by crazycs520** [comment]
I will impl `Concat`. [#3654](https://github.com/tikv/tikv/pull/3654)

**Comment by zhongleihe** [comment]
I am going to implement
  StrToDateDate
  StrToDateDatetime
  StrToDateDuration

**Comment by edwardpku** [comment]
I'd like to pick DateDiff as a ramp up task

**Comment by rleungx** [comment]
@edwardpku Awesome! Don't hesitate to ask if you have any questions.

**Comment by edwardpku** [comment]
> @edwardpku Awesome! Don't hesitate to ask if you have any questions.
Sure, I'm considering which approach to use
1) port from go implementation : https://github.com/pingcap/tidb/blob/32b1dbd8d59fbd725ec3f2971da2323cae0bf885/types/mytime.go#L196
2) duration https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=b7d42f750130e1353562b11b35e10af9

what do you think?

**Comment by breeswish** [comment]
@edwardpku I think currently it's fine to just use the simple version since TiKV does not support zero time as TiDB does and it doesn't help a lot to port the implementation.

**Comment by gaodayue** [comment]
I'd like to implement Locate2Args and Locate3Args.

**Comment by iosmanthus** [comment]
I would like to complete the missing part of encryption and here is a relative issue: https://github.com/tikv/tikv/issues/3875
* [ ] AesDecrypt
* [ ] AesEncrypt
* [ ] Password
* [ ] RandomBytes

But I have a question, the `Password` here, does it means we need a safe password-hashing like `bcrypt/PBKDF2`or something else @breeswish ?

**Comment by breeswish** [comment]
@iosmanthus Depends on whether or not TiDB supports it. I think you can forget it for now (lower priority)

**Comment by H-ZeX** [comment]
Hello. I would like to impl these functions
- [ ]  IntAnyValue
- [ ]  RealAnyValue
- [ ]  StringAnyValue
- [ ]  TimeAnyValue
- [ ]  IsIPv4Compat
- [ ]  IsIPv4Mapped

There are some questions:
  - Is it better to split such functions to different PR?
  - Is the feacture os *AnyValue same as [mysql's ANY_VALUE]( https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_any-value)

**Comment by twitu** [comment]
Hello. I can try to implement the toSeconds function.

**Comment by trabbart** [comment]
Hello, I would like to implement function TimeToSec.

**Comment by kunalmohan** [comment]
Hi! I would like to implement the `NullTimeDiff` function.

**Comment by breeswish** [comment]
Close for https://github.com/tikv/tikv/issues/5751
