### ISSUE TITLE
copr: Roadmap to chunk-based Enum/Set support in TiKV

### ISSUE THREAD

**Issue by Xuanwo** [tikv/tikv#9066]
## Goal

Implement RFC https://github.com/tikv/rfcs/pull/57

## Roadmap

- [x] Add Enum/Set type #8849 
- [x] Add ChunkedVecEnum/ChunkedVecSet type #8948 #8988 
- [x] Add enum/set into ScalarValue and VectorValue #9021
- [x] Implement enum/set related copr functions #9133
- [x] Implement enum/set related aggr functions
  - [x] Count #9143 
  - [x] First #9135 
  - [x] Sum #9148 #9184 
  - [x] Avg #9186 
  - [x] Max/Min #9146 #9184 

---

- [ ] Add `elems` in FieldType (tipb) 
- [ ] Export `elems` from praser to tipb (tidb)
- [ ] Extrace `elems` from FieldType to construct ChunkedVecEnum/ChunkedVecSet

**Comment by Xuanwo** [comment]
cc @skyzh @breeswish

**Comment by skyzh** [comment]
Looks good to me!

**Comment by skyzh** [comment]
Now we have implemented enum and set calculation on TiKV side, and this issue could be closed. The pushdown part is tracked at TiDB repo https://github.com/pingcap/tidb/issues/23619.
