### ISSUE TITLE
*: TiKV IO rate limiter - phase 1

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#9156]
## Development Task

The goal of the project is to provide a generic IO rate limiter within a TiKV process. Currently for separate tasks we have rate limiter of different form (e.g. rocksdb compaction IO rate limiter, BR/Lightning rate limiter). By providing a generate IO rate limiter we can have one single IO upper bound for all IO tasks. The project mainly target for users of cloud disk, such as EBS, where there's hard limit of IO bandwidth. But it would also be useful in general to have fine granularity control of TiKV IO behavior.

This issue tracks phase 1 of the IO rate limiter project, whose scope is described in the [spec](https://docs.google.com/document/d/1Jdsi7Ah1YtlZ3trCenqOL3BQ0FyeeubPJwyGwPeUdXM/edit?usp=sharing).

Tasks breakdown:
## interface
- [x] Rate limiter and file abstraction code skeleton @tabokie #9149 
## file system abstraction
- [x] File system abstraction - TiKV @tabokie #9149
- [x] File system abstraction - RocksDB @tabokie https://github.com/tikv/rocksdb/pull/216 https://github.com/tikv/rocksdb/pull/218 https://github.com/tikv/rust-rocksdb/pull/575 https://github.com/tikv/rust-rocksdb/pull/589 https://github.com/tikv/rust-rocksdb/pull/590
## tagging IO flows
- [x] Tag foreground read and coprocessor read @Connor1996 https://github.com/tikv/tikv/pull/9440
- [x] Tag foreground writes @Connor1996 https://github.com/tikv/tikv/pull/9440
- [x] Tag snapshot @Connor1996 https://github.com/tikv/tikv/pull/9440
- [x] Tag RocksDB flush and compaction @Connor1996 https://github.com/tikv/tikv/pull/9440
- [ ] Tag BR / Lightning / CDC
## measure IO throughput
- [x] Using bcc API to measure actual IO throughput @Connor1996 #9153 
- [x] Expose the metrics to Grafana, add dashboard @Connor1996 #9153
## rate limiter implementation
- [ ] Basic rate limiter implementation @tabokie #9197 
## integration test
- [ ] bank2
- [ ] Manual run TPCC and check metrics
- [ ] benchmark (surge of compaction, snapshot, GC) 
- [ ] benchmark (backup and restore, Lightning)

**Comment by yiwu-arbug** [comment]
This is done as of v5.1.0.
