### ISSUE TITLE
LFX: Implement Jepsen test for TiKV

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#9588]
## Description

TiDB has implemented tests with [`Jepsen`](https://github.com/jepsen-io/jepsen), a test framework for distributed systems, to guarantee its correctness. But there are also many TiKV adoptions that are using TiKV without TiDB, which are not covered so well by the Jepsen test for TiDB. Therefore, this program is to build a test framework using Jepsen and Rust client that tests against TiKV transaction API.

## Document Collection

- [Jepsen](https://github.com/jepsen-io/jepsen)
- [Program progress document](https://docs.google.com/document/d/18R-zaCiC4EvzpbRFndFjkpAQ11nwVdvP26g1zya604w/edit?usp=sharing)

## LFX Program information

- Mentor of this issue: @ekexium @andylokandy
- Recommended skills: Rust / Golang / Clojure
- Estimated Workloads: 3 Man-Month

## Milestones and action items

- [x]  setup and teardown of the TiKV cluster
- [x  operations on TiKV
    - [x] RawKV
          - [x] Read/Write
          - [x] CaS
    - [x] TxnKV 
- [x]  model and checker for TiKV
    - [x] RawKV
        - [x] Register (need CaS)
        - [x] Sets
    - [ ] TxnKV
        - [ ] [list-append](https://github.com/jepsen-io/scylla/blob/0fbf866f24e9d98553c4021a64d3f448147585a1/src/scylla/list_append.clj)
        - [ ] [wr-register](https://github.com/jepsen-io/scylla/blob/0fbf866f24e9d98553c4021a64d3f448147585a1/src/scylla/wr_register.clj)

**Comment by skyzh** [comment]
This is a project for [LFX Mentorship 2021 Q1](https://github.com/cncf/mentoring/blob/master/lfx-mentorship/2021/01-Spring/project_ideas.md#tikv). If you are interested in this, please refer to https://docs.google.com/document/d/1XawrFN5oiuPHxqwkd_3yz2b9n3oJNUh1MxCd0VtfU2E for more information.

**Comment by andylokandy** [comment]
This project has been tracing in [this document](https://docs.google.com/document/d/1sEShqIJapE_7UmFbls5hPwKqwYe96lKIHl-gjg3bg5o/edit#) for LFX program.
