### ISSUE TITLE
Roadmap: Jepsen test for TiKV

### ISSUE THREAD

**Issue by ziyi-yan** [tikv/tikv#9764]
## Development task

- [x]  setup and teardown of the TiKV cluster
- [ ]  operations on TiKV
    - [ ] RawKV
          - [x] Read/Write
          - [ ] CaS
    - [ ] TxnKV 
- [ ]  model and checker for TiKV
    - [ ] RawKV
        - [ ] Register (need CaS)
        - [ ] Sets
    - [ ] TxnKV
        - [ ] [list-append](https://github.com/jepsen-io/scylla/blob/0fbf866f24e9d98553c4021a64d3f448147585a1/src/scylla/list_append.clj)
        - [ ] [wr-register](https://github.com/jepsen-io/scylla/blob/0fbf866f24e9d98553c4021a64d3f448147585a1/src/scylla/wr_register.clj)

**Comment by andylokandy** [comment]
This is tracked by https://github.com/tikv/tikv/issues/9588
