### ISSUE TITLE
Load base split in 5.0

### ISSUE THREAD

**Issue by lhy1024** [tikv/tikv#9790]
## Development Task

- [x] Fix raw key mode in load-base-split #9662
- [x] Add end key as sample key in key range for load base split #9793
- [x] Add byte threshold and remove approximate threshold for load base split #9794
- [x] Add load-base-split test in test-custom.toml #9693
- [x] Add metrics for load base split #9768

**Comment by BusyJay** [comment]
Can it be closed now?
